version: "3.9"

services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: ms_mock_s3
    ports:
      - "8081:8080"
    volumes:
      - ../mock-server/mappings:/home/wiremock/mappings

  tests:
    build:
      context: ../../
      dockerfile: test-infra/docker/runner/Dockerfile
    container_name: ms_ci_tests

    depends_on:
      - wiremock

    cap_add:
      - NET_ADMIN
      - NET_RAW
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../src/allure-results:/allure-results
