version: "3.9"

services:
  db:
    build:
      context: ../docker/postgres
    container_name: ms_ci_db
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketstat"]
      interval: 3s
      timeout: 3s
      retries: 10
  
  api:
    build:
      context: ../../
      dockerfile: src/MarketStat/Dockerfile
    container_name: ms_ci_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__MarketStat=Host=db;Port=5432;Database=marketstat;Username=marketstat_analyst;Password=msanalyst
      - JwtSettings__Key=BiTFRKXvMfhuw3Juh6XrF4HE4Xd2-Ey98pS9QBsKfdo
      - JwtSettings__Issuer=marketstat-ci
      - JwtSettings__Audience=marketstat-ci
    ports:
      - "8080:8080"
  

  tests:
    build:
      context: ../docker/runner
    container_name: ms_ci_tests
    depends_on:
      api:
        condition: service_started
    network_mode: service:api
    environment:
      - ConnectionStrings__Admin=Host=db;Port=5432;Database=marketstat;Username=marketstat_administrator;Password=andresrmlnx15
      - E2E_BASE_URL=http://localhost:8080
    volumes:
      - ../../reports:/reports