version: "3.9"

services:
  tests:
    build:
      context: ../../
      dockerfile: test-infra/docker/runner/Dockerfile
    container_name: ms_ci_tests
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../src/allure-results:/allure-results
