version: "3.9"

services:
  db:
    build:
      context: ../docker/postgres
    container_name: ms_demo_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketstat"]
      interval: 3s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ../../
      dockerfile: src/MarketStat/Dockerfile
    container_name: ms_demo_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MarketStat=Host=db;Port=5432;Database=marketstat;Username=marketstat_analyst;Password=msanalyst
      - JwtSettings__Key=BiTFRKXvMfhuw3Juh6XrF4HE4Xd2-Ey98pS9QBsKfdo
      - JwtSettings__Issuer=marketstat-demo
      - JwtSettings__Audience=marketstat-demo

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: ms_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@marketstat.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      SCRIPT_NAME: /admin
    depends_on:
      - db

  gateway:
    image: nginx:alpine
    container_name: ms_gateway
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../docker/nginx/static:/usr/share/nginx/html
    depends_on:
      - api
      - pgadmin